//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nature.Chemkin.Thermo {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ThermoCollectionsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ThermoCollectionsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nature.Chemkin.Thermo.ThermoCollectionsResource", typeof(ThermoCollectionsResource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THERMO
        ///       300      1000      5000
        ///N2                000000N   2               G       300      5000    1000      1
        /// 2.92664000E+00 1.48797680E-03-5.68476000E-07 1.00970380E-10-6.75335100E-15    2
        ///-9.22797700E+02 5.98052800E+00 3.29867700E+00 1.40824040E-03-3.96322200E-06    3
        /// 5.64151500E-09-2.44485400E-12-1.02089990E+03 3.95037200E+00                   4
        ///AR                000000AR  1               G       300      5000    1000      1
        /// 2.50000000E+00 0.00000000E+00 0.00000000E+00 0.00000000E+00 0.000000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sandiego20160815_therm {
            get {
                return ResourceManager.GetString("sandiego20160815_therm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THERMO
        ///   300.000  1000.000  5000.000
        ///H                 120186H   1               G  0300.00   5000.00  1000.00      1
        /// 0.02500000E+02 0.00000000E+00 0.00000000E+00 0.00000000E+00 0.00000000E+00    2
        /// 0.02547162E+06-0.04601176E+01 0.02500000E+02 0.00000000E+00 0.00000000E+00    3
        /// 0.00000000E+00 0.00000000E+00 0.02547162E+06-0.04601176E+01                   4
        ///H2                121286H   2               G  0300.00   5000.00  1000.00      1
        /// 0.02991423E+02 0.07000644E-02-0.05633828E-06-0.09231578E-10 0.158275 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string thermmitsymp2004_dat {
            get {
                return ResourceManager.GetString("thermmitsymp2004_dat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THERMO
        ///   300.000  1000.000  5000.000
        ///! GRI-Mech Version 3.0 Thermodynamics released 7/30/99
        ///! NASA Polynomial format for CHEMKIN-II
        ///! see README file for disclaimer
        ///O                 L 1/90O   1               G   200.000  3500.000  1000.000    1
        /// 2.56942078E+00-8.59741137E-05 4.19484589E-08-1.00177799E-11 1.22833691E-15    2
        /// 2.92175791E+04 4.78433864E+00 3.16826710E+00-3.27931884E-03 6.64306396E-06    3
        ///-6.12806624E-09 2.11265971E-12 2.91222592E+04 2.05193346E+00                   4
        ///O2            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string thermo30 {
            get {
                return ResourceManager.GetString("thermo30", resourceCulture);
            }
        }
    }
}
